name: Build and Test

on: [pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.5'

      - name: Run tests
        run: |
          ./hack/verify-docfiles.sh && echo "Skipping build - only doc files have changed!" || \
            DOWNLOAD_BINARIES=y bash -x ./scripts/pre-commit.sh
